export default {
  Mpu: {
    Preharvestoperation:
      '- there is availability of human labour in Aninri so for all the pre-harvest operations, it’s more economical to hire labourers to till your field as there are no functional tractor hiring centres.- acquiring farm land is cheap and is more economical for a long term investment in farming. -purchasing your own tractors and other farm machines for personal use and leasing out will also be more profitable and lucrative.',
    Postharvestoperation:
      'you can create links with cassava processing companies and be one of their major suppliers.-all the operations in garri processing can be mechanized as there are  cassava peeling, washing & frying machines but the most suitable for you to adopt is the  frying machine for more faster production. The peeling and washing can be done manually at a cheaper cost.- the frying machines can be purchased online from Alibaba.com, madeinnigeria.com.ng etc. or fabricated locally.-Made in Nigeria garri fryers can be purchased for as low as #25000.- you should create your own brand, package it and sell by yourself or be supplying to supermarkets, hotels, restaurants etc.-A good percentage of cassava peels are usually thrown away in Aninri. You can process it into cassava peels cake. The wet cassava peels cake is used for feeding cows, goats, sheep and pigs with a shelf life of 7 days while the dried cassava peels cake can be milled and  sieved to get fine and coarse mash for poultry, fish , pigs, sheep , goat and cattle with a shelf life of 4-6 months.-Milling machines cost about #75000- #120000- For consultancy services, purchase of all agricultural machinery and farm equipment installation, spare parts  and farm machine servicing, contact the following companies through their respective contact address;Techo-Quip Nigeria Ltd (128, Ikotun-Idimu road, Akala Bus-stop, Idimu-Ikotun, Lagos, 0802 290 4222), (b) Nova Technologies (126, Oyo rd, Ajibode Bus-stop, Between UI 2nd gate and NISER, UI PO Box 19825, Ibadan, Oyo State, Nigeria, +234 (0) 803 3824 234, +234 (0) 805 5301 422 or www.novatechltd.com), (c)   S.Adiss Agricultural Engineering Limited (KM 10 along Ibadan/Lalupon road, Oganla village, Ibadan, Oyo State, 08023504754,08034102920,07035597702,08158162192,http://www.sadissengineering.com), (d) C-Woermann Nigeria (6 Badejo Kalesanwo Street, Matori industrial estate, Lagos, +234 1 2918597, services@woermann-nigeria.com), (e) Niji Group (10 Kufisile Street, Niji Lukas B/Stop, Isheri, Idimu, Lagos, +234-1-7743152, http://www.nijigroup.com), (f) Agro Nigerian Ventures Ltd.( 15 Odundun Street, Okesa, Ado-Ekiti, Ekiti State, +234 (0) 8022004111, http://www.anvltd.com), (g) . Deban Faith Agro-Allied Ventures (Km 1 Abeokuta – Lagos road, Oke Mosan behind Federal Secretariat Abeokuta, Ogun State, +2348030423532), (h) Debo farm (Gateway house, Ogbomosho, Oyo State, 08033060191, www.debofarm.com.ng) (i) Bertola Machine Tools (296, Ikorodu Road, Anthony. Box 2270, Ikeja, Lagos, +2348028476055, +234-18510876, www.bertolamachinetool.com), (j) Krishan Nigerian Limited (5-C, Ijora Causeway behind Leventis Cummins Africa, Ijora, Lagos, Nigeria, +234-1-72922874, 08033864984, 08034060107, www.krishannigeria.com).',
  },

  Ndeabor: {
    Preharvestoperation:
      'there is availability of human labour in Aninri so for all the pre-harvest operations, it’s more economical to hire labourers to till your field as there are no functional tractor hiring centres.- acquiring farm land is cheap and is more economical for a long term investment in farming. -purchasing your own tractors and other farm machines for personal use and leasing out will also be more profitable.',
    Postharvestoperation:
      'you can create links with cassava processing companies and be one of their major suppliers.-all the operations in garri processing can be mechanized as there are  cassava peeling, washing & frying machines but the most suitable for you to adopt is the  frying machine for more faster production. The peeling and washing can be done manually.- the frying machines can be purchased online from Alibaba.com, madeinnigeria.com.ng etc. or fabricated locally.-Made in Nigeria garri fryers can be purchased for as low as #25000.- you should create your own brand, package it and sell by yourself or be supplying to supermarkets, hotels, restaurants etc.-A good percentage of cassava peels are usually thrown away in Aninri. You can process it into cassava peels cake. The wet cassava peels cake is used for feeding cows, goats, sheep and pigs with a shelf life of 7 days while the dried cassava peels cake can be milled and  sieved to get fine and coarse mash for poultry, fish , pigs, sheep , goat and cattle with a shelf life of 4-6 months.-Milling machines cost about #75000- #120000- For consultancy services, purchase of all agricultural machinery and farm equipment, installation, spare parts  and farm machine servicing, contact the following companies through their respective contact address;Techo-Quip Nigeria Ltd (128, Ikotun-Idimu road, Akala Bus-stop, Idimu-Ikotun, Lagos, 0802 290 4222), (b) Nova Technologies (126, Oyo rd, Ajibode Bus-stop, Between UI 2nd gate and NISER, UI PO Box 19825, Ibadan, Oyo State, Nigeria, +234 (0) 803 3824 234, +234 (0) 805 5301 422 or www.novatechltd.com), (c)   S.Adiss Agricultural Engineering Limited (KM 10 along Ibadan/Lalupon road, Oganla village, Ibadan, Oyo State, 08023504754,08034102920,07035597702,08158162192,http://www.sadissengineering.com), (d) C-Woermann Nigeria (6 Badejo Kalesanwo Street, Matori industrial estate, Lagos, +234 1 2918597, services@woermann-nigeria.com), (e) Niji Group (10 Kufisile Street, Niji Lukas B/Stop, Isheri, Idimu, Lagos, +234-1-7743152, http://www.nijigroup.com), (f) Agro Nigerian Ventures Ltd.( 15 Odundun Street, Okesa, Ado-Ekiti, Ekiti State, +234 (0) 8022004111, http://www.anvltd.com), (g) . Deban Faith Agro-Allied Ventures (Km 1 Abeokuta – Lagos road, Oke Mosan behind Federal Secretariat Abeokuta, Ogun State, +2348030423532), (h) Debo farm (Gateway house, Ogbomosho, Oyo State, 08033060191, www.debofarm.com.ng) (i) Bertola Machine Tools (296, Ikorodu Road, Anthony. Box 2270, Ikeja, Lagos, +2348028476055, +234-18510876, www.bertolamachinetool.com), (j) Krishan Nigerian Limited (5-C, Ijora Causeway behind Leventis Cummins Africa, Ijora, Lagos, Nigeria, +234-1-72922874, 08033864984, 08034060107, www.krishannigeria.com).',
  },

  Nenwe: {
    Preharvestoperation:
      'for all the pre-harvest operations, it’s more advisable to use hoes, axes & cutlasses to cut down grasses, shrubs & prune trees. Use burning to remove debris, use knapsack sprayers to apply herbicides and pesticides.',
    Postharvestoperation:
      'you can create links with cassava processing companies and be one of their major suppliers.-all the operations in garri processing can be mechanized as there are  cassava peeling, washing & frying machines but the most suitable for you to adopt is the  frying machine for more faster production. The peeling and washing can be done manually.- the frying machines can be purchased online from Alibaba.com, madeinnigeria.com.ng etc. or fabricated locally.-Made in Nigeria garri fryers can be purchased for as low as #25000.- you should create your own brand, package it and sell by yourself or be supplying to supermarkets, hotels, restaurants etc.-A good percentage of cassava peels are usually thrown away in Aninri. You can process it into cassava peels cake. The wet cassava peels cake is used for feeding cows, goats, sheep and pigs with a shelf life of 7 days while the dried cassava peels cake can be milled and  sieved to get fine and coarse mash for poultry, fish , pigs, sheep , goat and cattle with a shelf life of 4-6 months.-Milling machines cost about #75000- #120000- For consultancy services, purchase of all agricultural machinery and farm equipment, installation, spare parts  and farm machine servicing, contact the following companies through their respective contact address;Techo-Quip Nigeria Ltd (128, Ikotun-Idimu road, Akala Bus-stop, Idimu-Ikotun, Lagos, 0802 290 4222), (b) Nova Technologies (126, Oyo rd, Ajibode Bus-stop, Between UI 2nd gate and NISER, UI PO Box 19825, Ibadan, Oyo State, Nigeria, +234 (0) 803 3824 234, +234 (0) 805 5301 422 or www.novatechltd.com), (c)   S.Adiss Agricultural Engineering Limited (KM 10 along Ibadan/Lalupon road, Oganla village, Ibadan, Oyo State, 08023504754,08034102920,07035597702,08158162192,http://www.sadissengineering.com), (d) C-Woermann Nigeria (6 Badejo Kalesanwo Street, Matori industrial estate, Lagos, +234 1 2918597, services@woermann-nigeria.com), (e) Niji Group (10 Kufisile Street, Niji Lukas B/Stop, Isheri, Idimu, Lagos, +234-1-7743152, http://www.nijigroup.com), (f) Agro Nigerian Ventures Ltd.( 15 Odundun Street, Okesa, Ado-Ekiti, Ekiti State, +234 (0) 8022004111, http://www.anvltd.com), (g) . Deban Faith Agro-Allied Ventures (Km 1 Abeokuta – Lagos road, Oke Mosan behind Federal Secretariat Abeokuta, Ogun State, +2348030423532), (h) Debo farm (Gateway house, Ogbomosho, Oyo State, 08033060191, www.debofarm.com.ng) (i) Bertola Machine Tools (296, Ikorodu Road, Anthony. Box 2270, Ikeja, Lagos, +2348028476055, +234-18510876, www.bertolamachinetool.com), (j) Krishan Nigerian Limited (5-C, Ijora Causeway behind Leventis Cummins Africa, Ijora, Lagos, Nigeria, +234-1-72922874, 08033864984, 08034060107, www.krishannigeria.com).',
  },

  Oduma: {
    Preharvestoperation:
      'there is availability of human labour in Aninri so for all the pre-harvest operations, it’s more economical to hire labourers to till your field as there are no functional tractor hiring centres.- acquiring farm land is cheap and is more economical for a long term investment in farming. -purchasing your own tractors and other farm machines for personal use and leasing out will also be more profitable.',
    Postharvestoperation:
      'you can create links with cassava processing companies and be one of their major suppliers.-all the operations in garri processing can be mechanized as there are  cassava peeling, washing & frying machines but the most suitable for you to adopt is the  frying machine for more faster production. The peeling and washing can be done manually.- the frying machines can be purchased online from Alibaba.com, madeinnigeria.com.ng etc. or fabricated locally.-Made in Nigeria garri fryers can be purchased for as low as #25000.- you should create your own brand, package it and sell by yourself or be supplying to supermarkets, hotels, restaurants etc.-A good percentage of cassava peels are usually thrown away in Aninri. You can process it into cassava peels cake. The wet cassava peels cake is used for feeding cows, goats, sheep and pigs with a shelf life of 7 days while the dried cassava peels cake can be milled and  sieved to get fine and coarse mash for poultry, fish , pigs, sheep , goat and cattle with a shelf life of 4-6 months.-Milling machines cost about #75000- #120000	For consultancy services, purchase of all agricultural machinery and farm equipment, installation, spare parts  and farm machine servicing, contact the following companies through their respective contact address;Techo-Quip Nigeria Ltd (128, Ikotun-Idimu road, Akala Bus-stop, Idimu-Ikotun, Lagos, 0802 290 4222), (b) Nova Technologies (126, Oyo rd, Ajibode Bus-stop, Between UI 2nd gate and NISER, UI PO Box 19825, Ibadan, Oyo State, Nigeria, +234 (0) 803 3824 234, +234 (0) 805 5301 422 or www.novatechltd.com), (c)   S.Adiss Agricultural Engineering Limited (KM 10 along Ibadan/Lalupon road, Oganla village, Ibadan, Oyo State, 08023504754,08034102920,07035597702,08158162192,http://www.sadissengineering.com), (d) C-Woermann Nigeria (6 Badejo Kalesanwo Street, Matori industrial estate, Lagos, +234 1 2918597, services@woermann-nigeria.com), (e) Niji Group (10 Kufisile Street, Niji Lukas B/Stop, Isheri, Idimu, Lagos, +234-1-7743152, http://www.nijigroup.com), (f) Agro Nigerian Ventures Ltd.( 15 Odundun Street, Okesa, Ado-Ekiti, Ekiti State, +234 (0) 8022004111, http://www.anvltd.com), (g) . Deban Faith Agro-Allied Ventures (Km 1 Abeokuta – Lagos road, Oke Mosan behind Federal Secretariat Abeokuta, Ogun State, +2348030423532), (h) Debo farm (Gateway house, Ogbomosho, Oyo State, 08033060191, www.debofarm.com.ng) (i) Bertola Machine Tools (296, Ikorodu Road, Anthony. Box 2270, Ikeja, Lagos, +2348028476055, +234-18510876, www.bertolamachinetool.com), (j) Krishan Nigerian Limited (5-C, Ijora Causeway behind Leventis Cummins Africa, Ijora, Lagos, Nigeria, +234-1-72922874, 08033864984, 08034060107, www.krishannigeria.com).',
  },

  Okpanku: {
    Preharvestoperation:
      'there is availability of human labour in Aninri so for all the pre-harvest operations, it’s more economical to hire labourers to till your field as there are no functional tractor hiring centres.- acquiring farm land is cheap and is more economical for a long term investment in farming. -purchasing your own tractors and other farm machines for personal use and leasing out will also be more profitable.',
    Postharvestoperation:
      '- you can create links with cassava processing companies and be one of their major suppliers.-all the operations in garri processing can be mechanized as there are  cassava peeling, washing & frying machines but the most suitable for you to adopt is the  frying machine for more faster production. The peeling and washing can be done manually.- the frying machines can be purchased online from Alibaba.com, madeinnigeria.com.ng etc. or fabricated locally.-Made in Nigeria garri fryers can be purchased for as low as #25000.- you should create your own brand, package it and sell by yourself or be supplying to supermarkets, hotels, restaurants etc.-A good percentage of cassava peels are usually thrown away in Aninri. You can process it into cassava peels cake. The wet cassava peels cake is used for feeding cows, goats, sheep and pigs with a shelf life of 7 days while the dried cassava peels cake can be milled and  sieved to get fine and coarse mash for poultry, fish , pigs, sheep , goat and cattle with a shelf life of 4-6 months.-Milling machines cost about #75000- #120000 For consultancy services, purchase of all agricultural machinery and farm equipment, installation, spare parts  and farm machine servicing, contact the following companies through their respective contact address;Techo-Quip Nigeria Ltd (128, Ikotun-Idimu road, Akala Bus-stop, Idimu-Ikotun, Lagos, 0802 290 4222), (b) Nova Technologies (126, Oyo rd, Ajibode Bus-stop, Between UI 2nd gate and NISER, UI PO Box 19825, Ibadan, Oyo State, Nigeria, +234 (0) 803 3824 234, +234 (0) 805 5301 422 or www.novatechltd.com), (c)   S.Adiss Agricultural Engineering Limited (KM 10 along Ibadan/Lalupon road, Oganla village, Ibadan, Oyo State, 08023504754,08034102920,07035597702,08158162192,http://www.sadissengineering.com), (d) C-Woermann Nigeria (6 Badejo Kalesanwo Street, Matori industrial estate, Lagos, +234 1 2918597, services@woermann-nigeria.com), (e) Niji Group (10 Kufisile Street, Niji Lukas B/Stop, Isheri, Idimu, Lagos, +234-1-7743152, http://www.nijigroup.com), (f) Agro Nigerian Ventures Ltd.( 15 Odundun Street, Okesa, Ado-Ekiti, Ekiti State, +234 (0) 8022004111, http://www.anvltd.com), (g) . Deban Faith Agro-Allied Ventures (Km 1 Abeokuta – Lagos road, Oke Mosan behind Federal Secretariat Abeokuta, Ogun State, +2348030423532), (h) Debo farm (Gateway house, Ogbomosho, Oyo State, 08033060191, www.debofarm.com.ng) (i) Bertola Machine Tools (296, Ikorodu Road, Anthony. Box 2270, Ikeja, Lagos, +2348028476055, +234-18510876, www.bertolamachinetool.com), (j) Krishan Nigerian Limited (5-C, Ijora Causeway behind Leventis Cummins Africa, Ijora, Lagos, Nigeria, +234-1-72922874, 08033864984, 08034060107, www.krishannigeria.com).',
  },
};
