export default {
  Mpu: {
    Preharvestoperation:
      'there is availability of human labour in Aninri so for all the pre-harvest operations, it’s more economical to hire labourers to till your field as there are no functional tractor hiring centres.-acquiring farm land is cheap and is more economical for a long term investment in farming. -purchasing your own tractors and other farm machines for personal use and leasing out will also be more profitable and lucrative.',
    Postharvestoperation:
      '-there is automatic potato chips line that combines all the processing operations such as that of cleaning & peeling, potato cutting, chips blanching, frying, de-oiling, flavouring, and chips packaging. -this machines can be purchased online.-processing the potato into flour is becoming lucrative nowadays. - For consultancy services, purchase of all agricultural machinery and farm equipment, installation, spare parts  and farm machine servicing, contact the following companies through their respective contact address;Techo-Quip Nigeria Ltd (128, Ikotun-Idimu road, Akala Bus-stop, Idimu-Ikotun, Lagos, 0802 290 4222), (b) Nova Technologies (126, Oyo rd, Ajibode Bus-stop, Between UI 2nd gate and NISER, UI PO Box 19825, Ibadan, Oyo State, Nigeria, +234 (0) 803 3824 234, +234 (0) 805 5301 422 or www.novatechltd.com), (c)   S.Adiss Agricultural Engineering Limited (KM 10 along Ibadan/Lalupon road, Oganla village, Ibadan, Oyo State, 08023504754,08034102920,07035597702,08158162192,http://www.sadissengineering.com), (d) C-Woermann Nigeria (6 Badejo Kalesanwo Street, Matori industrial estate, Lagos, +234 1 2918597, services@woermann-nigeria.com), (e) Niji Group (10 Kufisile Street, Niji Lukas B/Stop, Isheri, Idimu, Lagos, +234-1-7743152, http://www.nijigroup.com), (f) Agro Nigerian Ventures Ltd.( 15 Odundun Street, Okesa, Ado-Ekiti, Ekiti State, +234 (0) 8022004111, http://www.anvltd.com), (g) . Deban Faith Agro-Allied Ventures (Km 1 Abeokuta – Lagos road, Oke Mosan behind Federal Secretariat Abeokuta, Ogun State, +2348030423532), (h) Debo farm (Gateway house, Ogbomosho, Oyo State, 08033060191, www.debofarm.com.ng) (i) Bertola Machine Tools (296, Ikorodu Road, Anthony. Box 2270, Ikeja, Lagos, +2348028476055, +234-18510876, www.bertolamachinetool.com), (j) Krishan Nigerian Limited (5-C, Ijora Causeway behind Leventis Cummins Africa, Ijora, Lagos, Nigeria, +234-1-72922874, 08033864984, 08034060107, www.krishannigeria.com).',
  },

  Ndeabor: {
    Preharvestoperation:
      'there is availability of human labour in Aninri so for all the pre-harvest operations, it’s more economical to hire labourers to till your field as there are no functional tractor hiring centres.-acquiring farm land is cheap and is more economical for a long term investment in farming. -purchasing your own tractors and other farm machines for personal use and leasing out will also be more profitable and lucrative.',
    Postharvestoperation:
      '-there is automatic potato chips line that combines all the processing operations such as that of cleaning & peeling, potato cutting, chips blanching, frying, de-oiling, flavouring, and chips packaging. -this machines can be purchased online.-processing the potato into flour is becoming lucrative nowadays. - For consultancy services, purchase of all agricultural machinery and farm equipment, installation, spare parts  and farm machine servicing, contact the following companies through their respective contact address;Techo-Quip Nigeria Ltd (128, Ikotun-Idimu road, Akala Bus-stop, Idimu-Ikotun, Lagos, 0802 290 4222), (b) Nova Technologies (126, Oyo rd, Ajibode Bus-stop, Between UI 2nd gate and NISER, UI PO Box 19825, Ibadan, Oyo State, Nigeria, +234 (0) 803 3824 234, +234 (0) 805 5301 422 or www.novatechltd.com), (c)   S.Adiss Agricultural Engineering Limited (KM 10 along Ibadan/Lalupon road, Oganla village, Ibadan, Oyo State, 08023504754,08034102920,07035597702,08158162192,http://www.sadissengineering.com), (d) C-Woermann Nigeria (6 Badejo Kalesanwo Street, Matori industrial estate, Lagos, +234 1 2918597, services@woermann-nigeria.com), (e) Niji Group (10 Kufisile Street, Niji Lukas B/Stop, Isheri, Idimu, Lagos, +234-1-7743152, http://www.nijigroup.com), (f) Agro Nigerian Ventures Ltd.( 15 Odundun Street, Okesa, Ado-Ekiti, Ekiti State, +234 (0) 8022004111, http://www.anvltd.com), (g) . Deban Faith Agro-Allied Ventures (Km 1 Abeokuta – Lagos road, Oke Mosan behind Federal Secretariat Abeokuta, Ogun State, +2348030423532), (h) Debo farm (Gateway house, Ogbomosho, Oyo State, 08033060191, www.debofarm.com.ng) (i) Bertola Machine Tools (296, Ikorodu Road, Anthony. Box 2270, Ikeja, Lagos, +2348028476055, +234-18510876, www.bertolamachinetool.com), (j) Krishan Nigerian Limited (5-C, Ijora Causeway behind Leventis Cummins Africa, Ijora, Lagos, Nigeria, +234-1-72922874, 08033864984, 08034060107, www.krishannigeria.com).',
  },

  Nenwe: {
    Preharvestoperation:
      'there is availability of human labour in Aninri so for all the pre-harvest operations, it’s more economical to hire labourers to till your field as there are no functional tractor hiring centres.-acquiring farm land is cheap and is more economical for a long term investment in farming. -purchasing your own tractors and other farm machines for personal use and leasing out will also be more profitable and lucrative.',
    Postharvestoperation:
      '-there is automatic potato chips line that combines all the processing operations such as that of cleaning & peeling, potato cutting, chips blanching, frying, de-oiling, flavouring, and chips packaging. -this machines can be purchased online.-processing the potato into flour is becoming lucrative nowadays. - For consultancy services, purchase of all agricultural machinery and farm equipment, installation, spare parts  and farm machine servicing, contact the following companies through their respective contact address;Techo-Quip Nigeria Ltd (128, Ikotun-Idimu road, Akala Bus-stop, Idimu-Ikotun, Lagos, 0802 290 4222), (b) Nova Technologies (126, Oyo rd, Ajibode Bus-stop, Between UI 2nd gate and NISER, UI PO Box 19825, Ibadan, Oyo State, Nigeria, +234 (0) 803 3824 234, +234 (0) 805 5301 422 or www.novatechltd.com), (c)   S.Adiss Agricultural Engineering Limited (KM 10 along Ibadan/Lalupon road, Oganla village, Ibadan, Oyo State, 08023504754,08034102920,07035597702,08158162192,http://www.sadissengineering.com), (d) C-Woermann Nigeria (6 Badejo Kalesanwo Street, Matori industrial estate, Lagos, +234 1 2918597, services@woermann-nigeria.com), (e) Niji Group (10 Kufisile Street, Niji Lukas B/Stop, Isheri, Idimu, Lagos, +234-1-7743152, http://www.nijigroup.com), (f) Agro Nigerian Ventures Ltd.( 15 Odundun Street, Okesa, Ado-Ekiti, Ekiti State, +234 (0) 8022004111, http://www.anvltd.com), (g) . Deban Faith Agro-Allied Ventures (Km 1 Abeokuta – Lagos road, Oke Mosan behind Federal Secretariat Abeokuta, Ogun State, +2348030423532), (h) Debo farm (Gateway house, Ogbomosho, Oyo State, 08033060191, www.debofarm.com.ng) (i) Bertola Machine Tools (296, Ikorodu Road, Anthony. Box 2270, Ikeja, Lagos, +2348028476055, +234-18510876, www.bertolamachinetool.com), (j) Krishan Nigerian Limited (5-C, Ijora Causeway behind Leventis Cummins Africa, Ijora, Lagos, Nigeria, +234-1-72922874, 08033864984, 08034060107, www.krishannigeria.com).',
  },

  Oduma: {
    Preharvestoperation:
      'there is availability of human labour in Aninri so for all the pre-harvest operations, it’s more economical to hire labourers to till your field as there are no functional tractor hiring centres.-acquiring farm land is cheap and is more economical for a long term investment in farming. -purchasing your own tractors and other farm machines for personal use and leasing out will also be more profitable and lucrative.',
    Postharvestoperation:
      '-there is automatic potato chips line that combines all the processing operations such as that of cleaning & peeling, potato cutting, chips blanching, frying, de-oiling, flavouring, and chips packaging. -this machines can be purchased online.-processing the potato into flour is becoming lucrative nowadays. - For consultancy services, purchase of all agricultural machinery and farm equipment, installation, spare parts  and farm machine servicing, contact the following companies through their respective contact address;Techo-Quip Nigeria Ltd (128, Ikotun-Idimu road, Akala Bus-stop, Idimu-Ikotun, Lagos, 0802 290 4222), (b) Nova Technologies (126, Oyo rd, Ajibode Bus-stop, Between UI 2nd gate and NISER, UI PO Box 19825, Ibadan, Oyo State, Nigeria, +234 (0) 803 3824 234, +234 (0) 805 5301 422 or www.novatechltd.com), (c)   S.Adiss Agricultural Engineering Limited (KM 10 along Ibadan/Lalupon road, Oganla village, Ibadan, Oyo State, 08023504754,08034102920,07035597702,08158162192,http://www.sadissengineering.com), (d) C-Woermann Nigeria (6 Badejo Kalesanwo Street, Matori industrial estate, Lagos, +234 1 2918597, services@woermann-nigeria.com), (e) Niji Group (10 Kufisile Street, Niji Lukas B/Stop, Isheri, Idimu, Lagos, +234-1-7743152, http://www.nijigroup.com), (f) Agro Nigerian Ventures Ltd.( 15 Odundun Street, Okesa, Ado-Ekiti, Ekiti State, +234 (0) 8022004111, http://www.anvltd.com), (g) . Deban Faith Agro-Allied Ventures (Km 1 Abeokuta – Lagos road, Oke Mosan behind Federal Secretariat Abeokuta, Ogun State, +2348030423532), (h) Debo farm (Gateway house, Ogbomosho, Oyo State, 08033060191, www.debofarm.com.ng) (i) Bertola Machine Tools (296, Ikorodu Road, Anthony. Box 2270, Ikeja, Lagos, +2348028476055, +234-18510876, www.bertolamachinetool.com), (j) Krishan Nigerian Limited (5-C, Ijora Causeway behind Leventis Cummins Africa, Ijora, Lagos, Nigeria, +234-1-72922874, 08033864984, 08034060107, www.krishannigeria.com).',
  },

  Okpanku: {
    Preharvestoperation:
      'there is availability of human labour in Aninri so for all the pre-harvest operations, it’s more economical to hire labourers to till your field as there are no functional tractor hiring centres.-acquiring farm land is cheap and is more economical for a long term investment in farming. -purchasing your own tractors and other farm machines for personal use and leasing out will also be more profitable and lucrative.',
    Postharvestoperation:
      '-there is automatic potato chips line that combines all the processing operations such as that of cleaning & peeling, potato cutting, chips blanching, frying, de-oiling, flavouring, and chips packaging. -this machines can be purchased online.-processing the potato into flour is becoming lucrative nowadays. - For consultancy services, purchase of all agricultural machinery and farm equipment, installation, spare parts  and farm machine servicing, contact the following companies through their respective contact address;Techo-Quip Nigeria Ltd (128, Ikotun-Idimu road, Akala Bus-stop, Idimu-Ikotun, Lagos, 0802 290 4222), (b) Nova Technologies (126, Oyo rd, Ajibode Bus-stop, Between UI 2nd gate and NISER, UI PO Box 19825, Ibadan, Oyo State, Nigeria, +234 (0) 803 3824 234, +234 (0) 805 5301 422 or www.novatechltd.com), (c)   S.Adiss Agricultural Engineering Limited (KM 10 along Ibadan/Lalupon road, Oganla village, Ibadan, Oyo State, 08023504754,08034102920,07035597702,08158162192,http://www.sadissengineering.com), (d) C-Woermann Nigeria (6 Badejo Kalesanwo Street, Matori industrial estate, Lagos, +234 1 2918597, services@woermann-nigeria.com), (e) Niji Group (10 Kufisile Street, Niji Lukas B/Stop, Isheri, Idimu, Lagos, +234-1-7743152, http://www.nijigroup.com), (f) Agro Nigerian Ventures Ltd.( 15 Odundun Street, Okesa, Ado-Ekiti, Ekiti State, +234 (0) 8022004111, http://www.anvltd.com), (g) . Deban Faith Agro-Allied Ventures (Km 1 Abeokuta – Lagos road, Oke Mosan behind Federal Secretariat Abeokuta, Ogun State, +2348030423532), (h) Debo farm (Gateway house, Ogbomosho, Oyo State, 08033060191, www.debofarm.com.ng) (i) Bertola Machine Tools (296, Ikorodu Road, Anthony. Box 2270, Ikeja, Lagos, +2348028476055, +234-18510876, www.bertolamachinetool.com), (j) Krishan Nigerian Limited (5-C, Ijora Causeway behind Leventis Cummins Africa, Ijora, Lagos, Nigeria, +234-1-72922874, 08033864984, 08034060107, www.krishannigeria.com).',
  },
};
